### ISSUE TITLE
[BUG] Inventory full

### ISSUE THREAD

**Issue by maguhd** [DanielEscadas/conde-b1g_inventory#2]
Inventory is full and I can still get items into it.

How to check:
Get your items into your inventory untill it's full. Then go to a car trunk and deposit some in it. Leave trunk. Make sure your inventory is still full. And then go into the trunk again and try to take some items into the inventory.

**Comment by DanielEscadas** [comment]
Maguhd, ESX defines the weight limit, you will have to add this xPlayer method canCarryItem() that returns a bool to every time an item is given!
So for example 
if xPlayer.canCarryItem(item.name, item.count) then
... give item...
else
--- NOTIFY DOESNT HAVE SPACE IN THE INVENTORY
