### ISSUE TITLE
Can't seem to equip weapons

### ISSUE THREAD

**Issue by zeusemp** [DanielEscadas/conde-b1g_inventory#6]
I did the weapons as items, but when i try to equip it dosen't works, Any fix?

https://www.youtube.com/watch?v=UQdaLm0m2t4 Here's a preview

**Comment by DanielEscadas** [comment]
The inventory only works with wepons as Items! For now, mby will launch an update today with that!

**Comment by zeusemp** [comment]
Sweet!, thanks for the answer.

**Comment by DanielEscadas** [comment]
Solved
