### ISSUE TITLE
Bug with weight/shop's

### ISSUE THREAD

**Issue by ImpulseFPS** [DanielEscadas/conde-b1g_inventory#7]
So basically go to the shop try to buy 200 water you cant "there is not enough space in your inventory but if you go and do it by buying 20 water bottles you can stack them up to 1000k.
I hope you fix it soon.

Best regards
Impulse

**Comment by maguhd** [comment]
This doesn't happens to me.

**Comment by DanielEscadas** [comment]
Solved
